<a href="https://colab.research.google.com/github/poiuyytee/amulya/blob/main/ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Week 6: Training NN with Data

In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
dataset = pd.read_csv("/content/Iris.csv")

In [ ]:
#read the dataset
#dataset = pd.read_csv("CM.csv")
dataset.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  
0               1        101348.88       1  
1               1        112542.58       0  
2               0        113931.57       1  
3               0         93826.63       0  
4               1         79084.10       0

In [ ]:
#separate X and target
X = dataset.iloc[:,:8].values
y = dataset.iloc[:,-1].values

In [ ]:
print(X)

[[1 5.1 3.5 1.4 0.2 'Iris-setosa']
 [2 4.9 3.0 1.4 0.2 'Iris-setosa']
 [3 4.7 3.2 1.3 0.2 'Iris-setosa']
 [4 4.6 3.1 1.5 0.2 'Iris-setosa']
 [5 5.0 3.6 1.4 0.2 'Iris-setosa']
 [6 5.4 3.9 1.7 0.4 'Iris-setosa']
 [7 4.6 3.4 1.4 0.3 'Iris-setosa']
 [8 5.0 3.4 1.5 0.2 'Iris-setosa']
 [9 4.4 2.9 1.4 0.2 'Iris-setosa']
 [10 4.9 3.1 1.5 0.1 'Iris-setosa']
 [11 5.4 3.7 1.5 0.2 'Iris-setosa']
 [12 4.8 3.4 1.6 0.2 'Iris-setosa']
 [13 4.8 3.0 1.4 0.1 'Iris-setosa']
 [14 4.3 3.0 1.1 0.1 'Iris-setosa']
 [15 5.8 4.0 1.2 0.2 'Iris-setosa']
 [16 5.7 4.4 1.5 0.4 'Iris-setosa']
 [17 5.4 3.9 1.3 0.4 'Iris-setosa']
 [18 5.1 3.5 1.4 0.3 'Iris-setosa']
 [19 5.7 3.8 1.7 0.3 'Iris-setosa']
 [20 5.1 3.8 1.5 0.3 'Iris-setosa']
 [21 5.4 3.4 1.7 0.2 'Iris-setosa']
 [22 5.1 3.7 1.5 0.4 'Iris-setosa']
 [23 4.6 3.6 1.0 0.2 'Iris-setosa']
 [24 5.1 3.3 1.7 0.5 'Iris-setosa']
 [25 4.8 3.4 1.9 0.2 'Iris-setosa']
 [26 5.0 3.0 1.6 0.2 'Iris-setosa']
 [27 5.0 3.4 1.6 0.4 'Iris-setosa']
 [28 5.2 3.5 1.5 0.2 'Iris-setosa']
 

In [ ]:
print(y[0:5])

[1 0 1 0 0]


In [ ]:
# for our validation, convert X and y to dataframe and check the columns
df = pd.DataFrame(X)
df.head()

# observe X has 0 to 7 columns , so total of 8  columns in X

0    1    2    3    4            5
0  1  5.1  3.5  1.4  0.2  Iris-setosa
1  2  4.9  3.0  1.4  0.2  Iris-setosa
2  3  4.7  3.2  1.3  0.2  Iris-setosa
3  4  4.6  3.1  1.5  0.2  Iris-setosa
4  5  5.0  3.6  1.4  0.2  Iris-setosa

In [ ]:
df=pd.DataFrame(y)
df.head()
# y has only target

0
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [ ]:
# apply train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
#build your keras ANN model
import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# Defining the ANN model
model = Sequential()
# Adding the first hidden layer, by passing X with 8 features
model.add(Dense(units = 4, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
model.add(Dense(units = 4, kernel_initializer = 'uniform', activation = 'relu'))
#model.add(Dense(units = 4, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 4)                 36        
                                                                 
 dense_4 (Dense)             (None, 4)                 20        
                                                                 
 dense_5 (Dense)             (None, 1)                 5         
                                                                 
Total params: 61
Trainable params: 61
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# Fitting the ANN to the Training set
model.fit(X_train, y_train, batch_size = 2, epochs = 10)

ValueError: ignored

In [ ]:
y_pred = model.predict(X_test)


ValueError: ignored

In [ ]:

print(y_pred[10:20])

[[0.20113568]
 [0.31556407]
 [0.23711735]
 [0.22638437]
 [0.3322509 ]
 [0.30856797]
 [0.15664361]
 [0.31282458]
 [0.33201468]
 [0.32342416]]


In [ ]:
# Iterate over model layers
for layer in model.layers:
  print(layer.name, layer)

# firstlayer
print(model.layers[0].weights)
#print(model.layers[0].bias.numpy())
#print(model.layers[0].bias_initializer)

# secondlayer
print(model.layers[1].weights)
#print(model.layers[1].bias.numpy())
#print(model.layers[1].bias_initializer)

# lastlayer
print(model.layers[2].weights)
#print(model.layers[2].bias.numpy())
#print(model.layers[2].bias_initializer)

# firstlayer by name
print((model.get_layer("dense_7").weights))

# secondlayer by name
print((model.get_layer("dense_8").weights))

# lastlayer by name
print((model.get_layer("dense_9").weights))

dense_7 <keras.layers.core.dense.Dense object at 0x7b38b82ace80>
dense_8 <keras.layers.core.dense.Dense object at 0x7b38a8724af0>
dense_9 <keras.layers.core.dense.Dense object at 0x7b38a8724ca0>
[<tf.Variable 'dense_7/kernel:0' shape=(8, 4) dtype=float32, numpy=
array([[ 0.01491802,  0.34846944,  0.00710767,  0.02008521],
       [-0.04510038,  0.03375654, -0.12982401, -0.05024299],
       [-0.03019277,  0.49617973,  0.05698378, -0.00447106],
       [-0.0442013 , -0.02945803,  0.00897844, -0.00128035],
       [-0.02692081,  0.5467197 , -0.13953151,  0.03164689],
       [-0.02413525,  0.3531821 ,  0.05368862, -0.0095305 ],
       [ 0.04301095,  0.819184  ,  0.46187344,  0.01912863],
       [-0.02725021,  0.01697226,  0.01886184, -0.05160741]],
      dtype=float32)>, <tf.Variable 'dense_7/bias:0' shape=(4,) dtype=float32, numpy=array([ 0.        ,  0.31484208,  0.01334883, -0.00472312], dtype=float32)>]
[<tf.Variable 'dense_8/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.0086017

In [ ]:
print(y_test[10:20])

[0 0 0 0 0 0 1 0 0 0]


In [ ]:
# Evaluate the model
loss, accuracy = model.evaluate(X_train, y_train)
print("Train Loss:", loss)
print("Train Accuracy:", accuracy)

25/25 [==============================] - 0s 954us/step - loss: 0.5040 - accuracy: 0.7997
Train Loss: 0.5040314197540283
Train Accuracy: 0.7997496724128723


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, np.round(y_pred))
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[156   0]
 [ 44   0]]



#what is accuracy score formula?
#What is the loss function used?
#Analyse how  is confusion matrix computed?What is precision and recall?
#analyze how weights are updated at each epoch through backpropagation?




In [ ]:
# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

7/7 [==============================] - 0s 2ms/step - loss: 0.5416 - accuracy: 0.7800
Test Loss: 0.5416260361671448
Test Accuracy: 0.7799999713897705


In [ ]:
#ML techniques: SVC-Support Vector Classification
#from sklearn.svm import LinearSVC
#from sklearn.metrics import accuracy_score
#from sklearn.metrics import hinge_loss
#clf = LinearSVC(C=1,loss="hinge")
#clf.fit(X_train, y_train)

# Make predictions on the testing set
#y_pred = clf.predict(X_test)
#accuracy = accuracy_score(y_test, y_pred)

#print("Test Accuracy:", accuracy)
# Calculate the hinge loss
#avg_hinge_loss = hinge_loss(y_test, decision_scores)
#print("Test Loss:", avg_hinge_loss)

In [ ]:
#ML techniques: SVC-Support Vector Classification-2 using Standard scaler to center the training set around mean
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import hinge_loss
clf = Pipeline([("scaler", StandardScaler()),("linear_svc",LinearSVC(C=1,loss="hinge")),])
clf.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", accuracy)
decision_scores = clf.decision_function(X_test)

# Calculate the hinge loss
avg_hinge_loss = hinge_loss(y_test, decision_scores)
print("Test Loss:", avg_hinge_loss)

Test Accuracy: 0.78
Test Loss: 0.4400000000001058


In [ ]:
#ML techniques: Nonlinear SVC-Support Vector Classification
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import hinge_loss
clf = Pipeline([("scaler", StandardScaler()),("svm_clf",SVC(kernel="rbf",gamma=5,C=1)),])
clf.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", accuracy)
decision_scores = clf.decision_function(X_test)

# Calculate the hinge loss
avg_hinge_loss = hinge_loss(y_test, decision_scores)
print("Test Loss:", avg_hinge_loss)

Test Accuracy: 0.78
Test Loss: 0.5724151885384846


In [ ]:
#ML techniques: Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
clf = LogisticRegression(random_state=42)
clf.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
y_train_pred = clf.predict(X_train)
trainaccuracy = accuracy_score(y_train, y_train_pred)
print("Train Accuracy:", trainaccuracy)
print("Test Accuracy:", accuracy)

Train Accuracy: 0.7909887359198998
Test Accuracy: 0.765


In [ ]:
#ML techniques: Linear Discrminant Analysis
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import hinge_loss
# Create an instance of LinearDiscriminantAnalysis

clf = LinearDiscriminantAnalysis()
clf.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", accuracy)


Test Accuracy: 0.825


In [ ]:
#ML techniques: Linear Discrminant Analysis with Nonlinear SVC classifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import hinge_loss
# Create an instance of LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()

# Fit the LDA model on the training data
lda.fit(X_train, y_train)

# Transform the data using the LDA model
X_train_lda = lda.transform(X_train)
X_test_lda = lda.transform(X_test)
clf = Pipeline([("scaler", StandardScaler()),("svm_clf",SVC(kernel="rbf",gamma=5,C=1)),])
clf.fit(X_train_lda, y_train)

# Make predictions on the testing set
y_pred = clf.predict(X_test_lda)
accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", accuracy)
decision_scores = clf.decision_function(X_test_lda)

# Calculate the hinge loss
avg_hinge_loss = hinge_loss(y_test, decision_scores)
print("Test Loss:", avg_hinge_loss)

Test Accuracy: 0.835
Test Loss: 0.3536984461120886


In [ ]:
# ANN model to Logistic Regression
model = Sequential()
# Adding the first hidden layer, by passing X with 8 features
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 8))



# Compiling the ANN
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.fit(X_train, y_train, batch_size = 32, epochs = 10)
y_pred = model.predict(X_test)
model.summary()
# Evaluate the model
loss, accuracy = model.evaluate(X_train, y_train)
print("Train Loss:", loss)
print("Train Accuracy:", accuracy)
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

Epoch 1/10
25/25 [==============================] - 0s 1ms/step - loss: 1261.8462 - accuracy: 0.7997
Epoch 2/10
25/25 [==============================] - 0s 1ms/step - loss: 425.7177 - accuracy: 0.7785
Epoch 3/10
25/25 [==============================] - 0s 1ms/step - loss: 51.7498 - accuracy: 0.6208
Epoch 4/10
25/25 [==============================] - 0s 1ms/step - loss: 13.2551 - accuracy: 0.6033
Epoch 5/10
25/25 [==============================] - 0s 1ms/step - loss: 9.8333 - accuracy: 0.5895
Epoch 6/10
25/25 [==============================] - 0s 1ms/step - loss: 10.2902 - accuracy: 0.6020
Epoch 7/10
25/25 [==============================] - 0s 1ms/step - loss: 8.2125 - accuracy: 0.6220
Epoch 8/10
25/25 [==============================] - 0s 1ms/step - loss: 7.5201 - accuracy: 0.6158
Epoch 9/10
25/25 [==============================] - 0s 1ms/step - loss: 6.9754 - accuracy: 0.6783
Epoch 10/10
7/7 [==============================] - 0s 1ms/step
Model: "sequential_2"
_________________________

In [ ]:
                  ##############################################################################